export const actionTypes = {
    CREATE_NEW_ACC_START : 'CREATE_NEW_ACC_START',
    CREATE_NEW_ACC_SUCCESS: 'CREATE_NEW_ACC_SUCCESS',
    CREATE_NEW_ACC_FAIL: 'CREATE_NEW_ACC_FAIL',

    GET_USER_START: 'GET_USER_START',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAIL: 'GET_USER_FAIL',

    LOGIN_START: 'LOGIN_START',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'
}