export const actionTypes = {
    GET_LIST_PRODUCTS_START: "GET_LIST_PRODUCT_START",
    GET_LIST_PRODUCTS_SUCCESS: "GET_LIST_PRODUCTS_SUCCESS" ,
    GET_LIST_PRODUCTS_FAIL: "GET_LIST_PRODUCTS_FAIL",
    GET_LIST_CATEGORY_START: "GET_LIST_CATEGORY_START" ,
    GET_LIST_CATEGORY_SUCCESS: "GET_LIST_CATEGORY_SUCCESS" ,
    GET_LIST_CATEGORY_FAIL: "GET_LIST_CATEGORY_FAIL",
    GET_DETAIL_PRODUCT_START: "GET_DETAIL_PRODUCT_START",
    GET_DEATAIL_PRODUCT_SUCCESS: "GET_DEATAIL_PRODUCT_SUCCESS",
    GET_DETAIL_PRODUCT_FAIL: "GET_DETAIL_PRODUCT_FAIL",
    GET_PRODUCT_SEARCHED_START: "GET_PRODUCT_SEARCHED_START",
    GET_PRODUCT_SEARCHED_SUCCESS: "GET_PRODUCT_SEARCHED_SUCCESS",
    GET_PRODUCT_SEARCHED_FAIL: "GET_PRODUCT_SEARCHED_FAIL",

    CHECK_COURSE_CODE_START: "CHECK_COURSE_CODE_START",
    CHECK_COURSE_CODE_SUCCESS: "CHECK_COURSE_CODE_SUCCESS",
    CHECK_COURSE_CODE_FAIL: "CHECK_COURSE_CODE_FAIL",

    GET_LIST_LESSON_START: "GET_LIST_LESSON_START",
    GET_LIST_LESSON_SUCCESS: "GET_LIST_LESSON_SUCCESS",
    GET_LIST_LESSON_FAIL: "GET_LIST_LESSON_FAIL",

    GET_LIST_MY_COURSE_START: "GET_LIST_MY_COURSE_START",
    GET_LIST_MY_COURSE_SUCCESS: "GET_LIST_MY_COURSE_SUCCESS",
    GET_LIST_MY_COURSE_FAIL: "GET_LIST_MY_COURSE_FAIL",

    CREATE_FOLDER_START: "CREATE_FOLDER_START",
    CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
    CREATE_FOLDER_FAILE: "CREATE_FOLDER_FAIL",
}
