export const actionTypes = {
    GET_LIST_TEACHERS_START: "GET_LIST_TEACHER_START",
    GET_LIST_TEACHERS_SUCCESS: "GET_LIST_TEACHERS_SUCCESS" ,
    GET_LIST_TEACHERS_FAIL: "GET_LIST_TEACHERS_FAIL",
}
