export const actionTypes = {
    GET_USER_INFO_START: "GET_USER_INFO_START",
    GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS" ,
    GET_USER_INFO_FAIL: "GET_USER_INFO_FAIL",

    UPDATE_USER_INFO_START: "UPDATE_USER_INFO_START",
    UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS" ,
    UPDATE_USER_INFO_FAIL: "UPDATE_USER_INFO_FAIL",
}
